= Projektantrag digitale Schulwahl
Flora Dallinger
1.0, {docdate}: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font

Flora Dallinger 3ahif 18.10.2024

== Projektbeschreibung
Da vor kurzem die Schülervertretungswahlen an der HTL Leonding stattgefunden haben und schon
wieder einige Stunden für das analoge Wählen und Auszählen aufgwendet werden mussten, habe ich den Vorschlag,
diesen Vorgang **effizienter** zu gestalten. +
Vor allem in einer HTL mit dem Schwerpunkt Technik/Informatik ist es wichtig, analoge Prozesse zu digitalisieren
und somit eine Vorbildfunktion im Thema IT für andere Schulen zu schaffen. Mit dem Programm soll es möglich sein,+
die Schülervertretungswahl auf elektronischem Weg einfach und schnell abzuwickeln und nachvollziehbar zu gestalten.

== Zweck
Ziel des Projekts ist es, den aktuell noch komplizierten Ablaub der Wahl zu vereinfachen.  +
Bei Erfüllung dieses Punktes kann auch garantiert werden, dass die Wahlen viel schneller abgewickelt werden und keine Leerläufe entstehen. +
Zusätzlich besteht weniger die Gefahr, dass das Wahlergebnis falsch berechnet wird, da dies nun eine Rechenmaschine
übernimmt. Somit wird auch eine große Last sowohl von SchülerInnen und LehrerInnen als auch vom Sekretariat genommen.
Auch der Aspekt der Ressourcenschonung wird hiermit einbezogen. Bis jetzt musste für jede/n SchülerIn ein eigener Wahlzettel
ausgedruckt werden. Mit der elektronischen Variante fällt dies gänzlich weg. +
Mit Umsetzung dieses Projektes werden somit folgende Vorteile verwirklicht:


* Vereinfachung des Ablaufs der Schülervertretungswahl
* Reduzierung des Zeitverbrauchs
* Vermeidung von Rechenfehlern
* Entlastung für SchülerInnen und LehrerInnen
* Ressourcenschonung (z.B. Papier)

== Kunde/Stakeholder
Die Schulverwaltung ist verpflichtet eine SchülerInnenvertretungswahl durchzuführen. Dadurch glit diese als Kunde in dem Projekt.
Es liegt in ihrem Interesse die Wahl so zeitsparend, übersichtlich und nachvollziehbar wie möglich abzuhalten.

Die Stakeholder sind alle anderen Beteiligten:

* SchülerInnen
* LehrerInnen
* WahlkandidatInnen

== Endergebnis
.Konkretere Beschreibung
Zu Beginn werden bei dem Schulwahlprogramm die Zahl der anwesenden SchülerInnen pro Klasse eingetragen.
Danach wird ein Code generiert. Der Code soll eine Starteinheit haben, die je nach Klasse unterschiedlich ist.
Am Ende werden zwei individuelle Zahlen hinzugefügt, die nach Durchzählen der SchülerInnen erhoben werden können.
Mit dem jeweilig zufällig zugeteilten Code kann sich jede/r SchülerIn individuell und vor allem anonym einmalig anmelden. +
Der/die SchülerIn gelangt direkt zur Abstimmung und kann hier auswählen, wem er/sie welche Punkteanzahl gibt.
Um die Abstimmung leichter auslesbar zu gestalten, stehen die Namen der KandidatInnen bereits auf dem Screen und nur die +
Punkte können zugeteilt werden, die in einem eigenen Feld zur Auswahl stehen.


.Umzusetzendes
User Interface::
. Auswahl zwischen LehrerIn und SchülerIn
* Als LehrerIn
** Anmeldung
** Auswahl der Klasse
** Auswahl wie viele SchülerInnen präsent sind
** Generierung eines Codes
* Als SchülerIn
** Anmeldung durch den Code
** Punktevergabe
Backend::
. Überprüfungen
* Codes
** dürfen nicht doppelt vorkommen
** genausoviele Schüleranmeldungen über einen Code wie von der Lehrkraft angegeben
* Abstimmung
** Tabellen auf denen man ankreuzen kann wer wie viele Stimmen bekommt
** Keine gleiche Punkteanzahl für mehrere Personen
Optionale Erweiterung::
. Datenbanken
* Erleichterung des Prozesses
** Soll direkt angeben wie viele SchülerInnen maximal anwesend sein können

== Ablauf
. Kick off
. Durchführung mit Meilensteinen und regelmäßigen Teambesprechungen
.. Frontend
.. Backend
.. Zusammensetzung von Frontend und Backend
.. Testlauf
.. Optimierung
.. Einführung Datenbanken (optional)
.. Testlauf
.. Rollout



== Ressourcen
Meiner Schätzung nach wird ein Team von mindestens 2 bis maximal 4 Personen benötigt. Innbegriffen ist eine Projektleitung.
Zusätzlich ist ein/e ProjektkoordinatorIn zu bestimmen, der/die sich um die jährliche Abwicklung der Schulwahl kümmert. +
Zeitlich wird mit einem Aufwand für die Umsetzung von 15 Personentagen (1 pt = 8h) gerechnet.


== Konsequenzen bei Nichtdurchführung
Bei Nichtdurchführung des Projektes wird sich am aktuellen Ablauf der Wahlen nur wenig ändern. +
Ohne die Digitalisierung werden nur kleine Verbesserungen möglich sein während mit der Digitalisierung die Effizienz und
die Zeitersparnis enorm steigen werden.


== Quellen
* Erfahrung im Ferialpraktikum der Solvistas GmbH
* Das Buch 'Systemplanung und Projektentwicklung'
* https://asciidoctor.org/docs/asciidoc-writers-guide/[*Asciidoc Tutorial*^]
